### ISSUE TITLE
custom_archive option in source installer

### ISSUE THREAD

**Issue by h416** [sprinkle-tool/sprinkle#141]
custom_archive option in source installer doesn't work since version 0.6.
It worked in version 0.5.2

```
package :cpulimit do
  source "https://github.com/opsengine/cpulimit/archive/master.zip" do
    custom_archive 'cpulimit-master.zip'
    custom_install "make && cp src/cpulimit /usr/bin/"
  end
  verify { has_executable "/usr/bin/cpulimit" }
end
```

error:

```
sprinkle-0.7.3/vendor/bundler/ruby/2.0.0/gems/sprinkle-0.7.3/lib/sprinkle/installers/installer.rb:117:in `method_missing': undefined method `custom_archive' for #<Sprinkle::Installers::Source:0x007fa00bd333a0> (NoMethodError)
```

Adding custom_archive attribute to source.rb fix this issue.

attributes :configure_command, :build_command, :install_command

->

attributes :configure_command, :build_command, :install_command, **:custom_archive**
